const initialValues = {
  name: "",
  rollNo: "",
  course: "",
  branch: "",
  semester: "",
  dateOfBirth: "",
  age: "",
  mobile: "",
  email: "",
  admissionCategory: "",
  bloodGroup: "",
  medicalHistory: "",
  previousResident: "",
  fatherName: "",
  fatherContactLocal: "",
  fatherContactForeign: "",
  motherName: "",
  motherContactLocal: "",
  landline: "",
  parentEmail: "",
  occupation: "",
  residentialAddress: "",
  pin: "",
  guardianName: "",
  guardianOccupation: "",
  guardianResidentialAddress: "",
  guardianPin: "",
  guardianMobile: "",
  guardianLandline: "",
  guardianEmail: "",
  hostelBlock: "",
  roomNumber: "",
  messPreference: "",
  declaration: [] as string[],
  passportPhoto: "",
  studentSignature: "",
  parentGuardianSignature: "",
};
export default initialValues;
