CREATE TYPE "public"."approval_status" AS ENUM('0', '1', '2', '3', '4');--> statement-breakpoint
CREATE TYPE "public"."role" AS ENUM('STUDENT', 'RC', 'DEPUTY_WARDEN', 'EXECUTIVE_WARDEN');--> statement-breakpoint
CREATE TABLE "admission" (
	"user_id" integer NOT NULL,
	"approval" "approval_status" NOT NULL,
	"payment_id" varchar NOT NULL,
	"name" varchar(100) NOT NULL,
	"roll_no" varchar(20) NOT NULL,
	"course" varchar(50) NOT NULL,
	"branch" varchar(50) NOT NULL,
	"semester" varchar(10) NOT NULL,
	"date_of_birth" date NOT NULL,
	"age" integer NOT NULL,
	"mobile" varchar(15) NOT NULL,
	"email" varchar(100) NOT NULL,
	"emergency_contact" varchar(15) NOT NULL,
	"nationality" varchar(50) NOT NULL,
	"govt_id" varchar(50) NOT NULL,
	"admission_category" varchar(20) NOT NULL,
	"blood_group" varchar(10) NOT NULL,
	"medical_history" text NOT NULL,
	"previous_resident" boolean NOT NULL,
	"hostel_block" varchar(20) NOT NULL,
	"room_number" varchar(10) NOT NULL,
	"mess_preference" varchar(20) NOT NULL,
	"father_name" varchar(100) NOT NULL,
	"father_occupation" varchar(100) NOT NULL,
	"father_mobile" varchar(15) NOT NULL,
	"father_email" varchar(100) NOT NULL,
	"father_country" varchar(50) NOT NULL,
	"mother_name" varchar(100) NOT NULL,
	"mother_occupation" varchar(100) NOT NULL,
	"mother_mobile" varchar(15) NOT NULL,
	"mother_email" varchar(100) NOT NULL,
	"mother_country" varchar(50) NOT NULL,
	"res_india_house_no" varchar(100) NOT NULL,
	"res_india_street" varchar(100) NOT NULL,
	"res_india_city" varchar(50) NOT NULL,
	"res_india_state" varchar(50) NOT NULL,
	"res_india_country" varchar(50) NOT NULL,
	"res_india_postal_code" varchar(20) NOT NULL,
	"res_foreign_house_no" varchar(100),
	"res_foreign_street" varchar(100),
	"res_foreign_city" varchar(50),
	"res_foreign_state" varchar(50),
	"res_foreign_country" varchar(50),
	"res_foreign_postal_code" varchar(20),
	"local_guardian_name" varchar(100),
	"local_guardian_relationship" varchar(50),
	"local_guardian_mobile" varchar(15),
	"local_guardian_email" varchar(100),
	"guardian_house_no" varchar(100),
	"guardian_street" varchar(100),
	"guardian_city" varchar(50),
	"guardian_state" varchar(50),
	"guardian_country" varchar(50),
	"guardian_postal_code" varchar(20),
	"student_declaration" boolean NOT NULL,
	"parent_declaration" boolean NOT NULL,
	"created_at" date DEFAULT now() NOT NULL,
	"transaction_id" varchar(100) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "readmission" (
	"user_id" serial PRIMARY KEY NOT NULL,
	"approval" "approval_status" NOT NULL,
	"academic_year" varchar(4) NOT NULL,
	"payment_id" serial NOT NULL,
	"student_name" text NOT NULL,
	"course" varchar(10) NOT NULL,
	"branch" varchar(50) NOT NULL,
	"year" varchar(2) NOT NULL,
	"semester" varchar(2) NOT NULL,
	"student_mobile" varchar(15) NOT NULL,
	"student_email" varchar(100) NOT NULL,
	"parent_mobile_1" varchar(15) NOT NULL,
	"parent_mobile_2" varchar(15),
	"parent_email" varchar(100),
	"guardian_name" text,
	"guardian_mobile" varchar(15),
	"address" text NOT NULL,
	"hostel_block" varchar(50) NOT NULL,
	"room_number" varchar(10) NOT NULL,
	"key_received" boolean NOT NULL,
	"fees_paid" boolean NOT NULL,
	"transaction_reference_no" varchar(50),
	"transaction_date" date,
	"amount" integer,
	"any_dues" boolean NOT NULL,
	"student_agreed" boolean NOT NULL,
	"parent_agreed" boolean NOT NULL,
	"submission_date" date NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(100) NOT NULL,
	"email" varchar(100) NOT NULL,
	"password" text NOT NULL,
	"role" varchar(20) DEFAULT 'student' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "grievances" (
	"room_id" integer NOT NULL,
	"user_id" integer,
	"description" text NOT NULL,
	"supportive_image" text,
	"title" varchar(100) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "admission" ADD CONSTRAINT "admission_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;