CREATE TYPE "public"."approval_status" AS ENUM('1', '2', '3');--> statement-breakpoint
CREATE TYPE "public"."role" AS ENUM('STUDENT', 'RC', 'DEPUTY_WARDEN', 'EXECUTIVE_WARDEN');--> statement-breakpoint
CREATE TABLE "admission" (
	"user_id" serial PRIMARY KEY NOT NULL,
	"approval" "approval_status" NOT NULL,
	"academic_year" varchar(4) NOT NULL,
	"payment_id" serial NOT NULL,
	"name" varchar(100) NOT NULL,
	"roll_no" varchar(20) NOT NULL,
	"course" varchar(50) NOT NULL,
	"branch" varchar(50) NOT NULL,
	"semester" varchar(10) NOT NULL,
	"date_of_birth" date NOT NULL,
	"age" integer NOT NULL,
	"mobile" varchar(15) NOT NULL,
	"email" varchar(100) NOT NULL,
	"admission_category" varchar(20) NOT NULL,
	"blood_group" varchar(10) NOT NULL,
	"medical_history" text NOT NULL,
	"previous_resident" boolean NOT NULL,
	"father_name" varchar(100) NOT NULL,
	"father_contact_local" varchar(15) NOT NULL,
	"father_contact_foreign" varchar(15),
	"mother_name" varchar(100) NOT NULL,
	"mother_contact_local" varchar(15) NOT NULL,
	"landline" varchar(15),
	"parent_email" varchar(100) NOT NULL,
	"occupation" varchar(100) NOT NULL,
	"residential_address" text NOT NULL,
	"pin" varchar(10) NOT NULL,
	"guardian_name" varchar(100),
	"guardian_occupation" varchar(100),
	"guardian_residential_address" text,
	"guardian_pin" varchar(10),
	"guardian_mobile" varchar(15),
	"guardian_landline" varchar(15),
	"guardian_email" varchar(100),
	"hostel_block" varchar(20) NOT NULL,
	"room_number" varchar(10) NOT NULL,
	"mess_preference" varchar(20) NOT NULL,
	"declaration" jsonb NOT NULL,
	"passport_photo" text NOT NULL,
	"student_signature" text NOT NULL,
	"parent_guardian_signature" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "readmission" (
	"user_id" serial PRIMARY KEY NOT NULL,
	"approval" "approval_status" NOT NULL,
	"academic_year" varchar(4) NOT NULL,
	"payment_id" serial NOT NULL,
	"student_name" text NOT NULL,
	"course" varchar(10) NOT NULL,
	"branch" varchar(50) NOT NULL,
	"year" varchar(2) NOT NULL,
	"semester" varchar(2) NOT NULL,
	"student_mobile" varchar(15) NOT NULL,
	"student_email" varchar(100) NOT NULL,
	"parent_mobile_1" varchar(15) NOT NULL,
	"parent_mobile_2" varchar(15),
	"parent_email" varchar(100),
	"guardian_name" text,
	"guardian_mobile" varchar(15),
	"address" text NOT NULL,
	"hostel_block" varchar(50) NOT NULL,
	"room_number" varchar(10) NOT NULL,
	"key_received" boolean NOT NULL,
	"fees_paid" boolean NOT NULL,
	"transaction_reference_no" varchar(50),
	"transaction_date" date,
	"amount" integer,
	"any_dues" boolean NOT NULL,
	"student_signature_url" text,
	"parent_guardian_signature_url" text,
	"student_agreed" boolean NOT NULL,
	"parent_agreed" boolean NOT NULL,
	"submission_date" date NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" varchar(50) NOT NULL,
	"password" varchar(255) NOT NULL,
	"email" varchar(100) NOT NULL,
	"role" "role" NOT NULL,
	CONSTRAINT "user_username_unique" UNIQUE("username"),
	CONSTRAINT "user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "grievances" (
	"room_id" integer NOT NULL,
	"user_id" integer,
	"description" text NOT NULL,
	"supportive_image" text,
	"title" varchar(100) NOT NULL
);
